<?php
namespace Buybrain\Buybrain;

use Buybrain\Buybrain\Util\DateTimes;
use DateTimeInterface;

/**
 * Representation of a sales forecast for a single article, generated by the buybrain system
 */
class SalesForecast implements BuybrainEntity
{
    const ENTITY_TYPE = 'salesForecast';

    use AsNervusEntityTrait;
    use EntityIdFactoryTrait;

    /** @var string */
    private $id;
    /** @var DateTimeInterface */
    private $createDate;
    /** @var string */
    private $modelId;
    /** @var string */
    private $sku;
    /** @var SalesForecastPeriod[] */
    private $periods;

    /**
     * @param string $id
     * @param DateTimeInterface $createDate
     * @param string $modelId
     * @param string $sku
     * @param SalesForecastPeriod[] $periods
     */
    public function __construct($id, DateTimeInterface $createDate, $modelId, $sku, array $periods)
    {
        $this->id = $id;
        $this->createDate = $createDate;
        $this->modelId = $modelId;
        $this->sku = $sku;
        $this->periods = $periods;
    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return DateTimeInterface
     */
    public function getCreateDate()
    {
        return $this->createDate;
    }

    /**
     * @return string
     */
    public function getModelId()
    {
        return $this->modelId;
    }

    /**
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * @return SalesForecastPeriod[]
     */
    public function getPeriods()
    {
        return $this->periods;
    }

    /**
     * @return array
     */
    public function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'createDate' => DateTimes::format($this->createDate),
            'modelId' => $this->modelId,
            'sku' => $this->sku,
            'periods' => $this->periods
        ];
    }

    /**
     * Create a SalesForecast instance from parsed JSON
     *
     * @param array $json
     * @return SalesForecast
     */
    public static function fromJson(array $json)
    {
        return new self(
            $json['id'],
            DateTimes::parse($json['createDate']),
            $json['modelId'],
            $json['sku'],
            array_map([SalesForecastPeriod::class, 'fromJson'], $json['periods'])
        );
    }
}
