<?php
namespace Buybrain\Buybrain;

use Buybrain\Buybrain\Util\DateTimes;
use DateTimeInterface;

/**
 * Representation of a sales forecast for a single article, generated by the buybrain system
 *
 * @link https://buybrain.io/docs#type-sales-forecasts
 */
class SalesForecast implements BuybrainEntity
{
    const ENTITY_TYPE = 'salesForecast';

    use AsNervusEntityTrait;
    use EntityIdFactoryTrait;

    /** @var string */
    private $id;
    /** @var DateTimeInterface */
    private $createDate;
    /** @var string */
    private $modelId;
    /** @var string */
    private $sku;
    /** @var string */
    private $channel;
    /** @var SalesForecastPeriod[] */
    private $periods;

    /**
     * @param string $id
     * @param DateTimeInterface $createDate
     * @param string $modelId
     * @param string $sku
     * @param string $channel
     * @param SalesForecastPeriod[] $periods
     */
    public function __construct($id, DateTimeInterface $createDate, $modelId, $sku, $channel, array $periods)
    {
        $this->id = (string)$id;
        $this->createDate = $createDate;
        $this->modelId = (string)$modelId;
        $this->sku = (string)$sku;
        $this->channel = (string)$channel;
        $this->periods = $periods;
    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return DateTimeInterface
     */
    public function getCreateDate()
    {
        return $this->createDate;
    }

    /**
     * @return string
     */
    public function getModelId()
    {
        return $this->modelId;
    }

    /**
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * @return SalesForecastPeriod[]
     */
    public function getPeriods()
    {
        return $this->periods;
    }

    /**
     * @return array
     */
    public function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'createDate' => DateTimes::format($this->createDate),
            'modelId' => $this->modelId,
            'sku' => $this->sku,
            'channel' => $this->channel,
            'periods' => $this->periods
        ];
    }

    /**
     * Create a SalesForecast instance from parsed JSON.
     * This class can be subclassed, and the subclass will be instantiated.
     *
     * @param array $json
     * @return static
     */
    public static function fromJson(array $json)
    {
        return new static(
            $json['id'],
            DateTimes::parse($json['createDate']),
            $json['modelId'],
            $json['sku'],
            $json['channel'],
            array_map([SalesForecastPeriod::class, 'fromJson'], $json['periods'])
        );
    }
}
